# Generated by Django 6.0.6 on 2026-07-06 02:40

import biblioteca.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='La matricula debe contener exactamente 9 digitos numericos.', regex='^\\d{9}$')])),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El telefono debe contener solo digitos (7 a 15).', regex='^\\d{7,15}$')])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', biblioteca.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('usuario_sistema', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('BIBLIOTECARIO', 'Bibliotecario')], default='BIBLIOTECARIO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='bibliotecarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='bibliotecarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Bibliotecario',
                'verbose_name_plural': 'Bibliotecarios',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', biblioteca.models.BibliotecarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=20, unique=True, validators=[biblioteca.models.validar_isbn])),
                ('fecha_publicacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='biblioteca.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='biblioteca.categoria')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_dev_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PROXIMO_A_VENCER', 'Proximo a vencer'), ('CERRADO', 'Cerrado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_gestionados', to='biblioteca.bibliotecario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_atraso', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('justificacion_anulacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='biblioteca.prestamo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_devolucion', models.DateField()),
                ('condicion', models.CharField(max_length=255)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='biblioteca.prestamo')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['usuario', 'estado'], name='biblioteca__usuario_88bede_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('libro',), name='unico_prestamo_activo_por_libro'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_dev_esperada__gt', models.F('fecha_inicio'))), name='fecha_dev_esperada_posterior_a_fecha_inicio'),
        ),
        migrations.AddConstraint(
            model_name='multa',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('prestamo',), name='unica_multa_pendiente_por_prestamo'),
        ),
    ]
