# Generated by Django 6.0.6 on 2026-07-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='bibliotecario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_gestionados', to='biblioteca.bibliotecario'),
        ),
    ]
