# Generated by Django 6.0.6 on 2026-07-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_prestamo_bibliotecario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_multa_diaria', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_maximos_prestamo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Configuracion de la Biblioteca',
                'verbose_name_plural': 'Configuracion de la Biblioteca',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
